### ISSUE TITLE
Make a template content repository for testing the NEBULA platform and creating other content repositories

### ISSUE THREAD

**Issue by JaroCamphuijsen** [esciencecenter-digital-skills/NEBULA#21]
Previously we used the content folder in the framework for dummy content.
Currently, we use the research software support content repository for the example content.

We should have an example/template repository for creating these websites, which contains some demo content.
Then we can also remove the dummy_deploy workflow from this repository and it won't need an actual gh-pages website.

**Comment by Cmurilochem** [comment]
Issue addressed in https://github.com/esciencecenter-digital-skills/NEBULA-content-template
