### ISSUE TITLE
GitHub pages link points to RSS: Is this the intended behaviour?

### ISSUE THREAD

**Issue by Cmurilochem** [esciencecenter-digital-skills/NEBULA#49]
The GitHub pages link of the NEBULA directory points directly to RSS [esciencecenter-digital-skills.github.io/NEBULA/](https://esciencecenter-digital-skills.github.io/NEBULA/).

I am not sure if this is the intended behaviour, but I do not see any other better alternative either since NEBULA needs to have a content to render.

Creating this issue for future reflection...

**Comment by JaroCamphuijsen** [comment]
Yeah good one, I think we can use the content template repository instead to make it a bit more neutral.

**Comment by JaroCamphuijsen** [comment]
We are now using the template content instead of the research software support.
